___
# Tratamento de dados
___

In [16]:
import pandas as pd

Importando os df e visualizando as tabelas

In [17]:
df_customer=pd.read_csv('https://raw.githubusercontent.com/VictorOliBar/Python/refs/heads/Tratamento-de-dados/E-Commerce%20Sales%20Analytics%20Dataset/customer_master.csv')

df_sales=pd.read_csv('https://raw.githubusercontent.com/VictorOliBar/Python/refs/heads/Tratamento-de-dados/E-Commerce%20Sales%20Analytics%20Dataset/ecommerce_sales_customer_analytics_150k.csv')

df_order=pd.read_csv('https://raw.githubusercontent.com/VictorOliBar/Python/refs/heads/Tratamento-de-dados/E-Commerce%20Sales%20Analytics%20Dataset/order_items.csv')

df_catalog=pd.read_csv('https://raw.githubusercontent.com/VictorOliBar/Python/refs/heads/Tratamento-de-dados/E-Commerce%20Sales%20Analytics%20Dataset/product_catalog.csv')

print('=-'*30 ,'Data frame CUSTOMER','=-'*30 )
display(df_customer,)

print('=-'*30 ,'Data frame SALES','=-'*30 )
display(df_sales)

print('=-'*30 ,'Data frame ORDER','=-'*30 )
display(df_order)

print('=-'*30 ,'Data frame CATALOG','=-'*30 )
display(df_catalog)

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- Data frame CUSTOMER =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...,...
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- Data frame SALES =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,8.84,14.28,6.15,224.42,101.77,116.50,51.91,18182.63,True,14
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,0.00,147.30,9.18,2260.80,1246.73,1004.89,44.45,10004.74,True,10
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,0.00,372.37,26.94,2261.16,970.95,1263.27,55.87,16442.68,True,15
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,174.60,130.58,84.39,2080.38,1042.40,953.59,45.84,8047.00,True,5
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,417.27,102.26,9.09,1572.22,884.46,678.67,43.17,4107.38,True,5

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- Data frame ORDER =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

,order_id,product_id,quantity,unit_price,discount_percentage,discount_amount,gross_sales,tax_amount,shipping_cost,net_sales,product_cost,profit
0,ORD-301242,PROD-000738,2,244.40,0.339607,166.00,488.80,22.60,6.48,351.88,173.28,172.12
1,ORD-301242,PROD-000181,3,287.13,0.362076,311.89,861.39,38.47,5.55,593.52,415.05,172.92
2,ORD-773460,PROD-000973,4,754.80,0.468300,1413.89,3019.20,305.01,9.00,1919.32,1976.16,-65.84
3,ORD-773460,PROD-000268,4,31.36,0.336182,42.17,125.44,15.82,0.00,99.09,55.72,43.37
4,ORD-449374,PROD-001040,3,6.31,0.089678,1.70,18.93,1.21,0.98,19.42,5.91,12.53
...,...,...,...,...,...,...,...,...,...,...,...,...
397564,ORD-252033,PROD-000792,2,137.53,0.156007,42.91,275.06,16.25,6.21,254.61,142.54,105.86
397565,ORD-252033,PROD-000804,5,118.96,0.097011,57.70,594.80,37.60,14.89,589.59,280.80,293.90
397566,ORD-252033,PROD-000527,3,52.50,0.141821,22.34,157.50,9.46,23.86,168.48,64.47,80.15
397567,ORD-528577,PROD-000004,1,1120.49,0.075121,84.17,1120.49,72.54,3.33,1112.19,564.86,544.00
397568,ORD-528577,PROD-000357,5,151.53,0.439653,333.10,757.65,29.72,5.76,460.03,319.60,134.67

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- Data frame CATALOG =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

,product_id,product_name,product_category,product_subcategory,brand,supplier,unit_price,product_cost,product_rating
0,PROD-000001,Apple Sharable bifurcated algorithm Smartphones,Electronics,Smartphones,Apple,Alibaba,686.90,474.06,4.3
1,PROD-000002,Google User-centric even-keeled encryption Sma...,Electronics,Smartphones,Google,Euro Logistics,978.26,519.66,2.9
2,PROD-000003,LG Face-to-face client-driven support Smartphones,Electronics,Smartphones,LG,Asian Manufacturing,275.51,185.48,3.9
3,PROD-000004,Sony Customer-focused systematic support Smart...,Electronics,Smartphones,Sony,Amazon Supply,1120.49,564.86,4.8
4,PROD-000005,OnePlus Quality-focused background parallelism...,Electronics,Smartphones,OnePlus,Direct Import,1282.18,695.54,2.9
...,...,...,...,...,...,...,...,...,...
1170,PROD-001171,Avery Inverse 4thgeneration productivity Calen...,Office Supplies,Calendars,Avery,Amazon Supply,107.23,33.97,4.8
1171,PROD-001172,Staples Future-proofed zero tolerance knowledg...,Office Supplies,Calendars,Staples,Pacific Trade,246.92,126.70,4.8
1172,PROD-001173,Mead Pre-emptive discrete help-desk Calendars,Office Supplies,Calendars,Mead,Alibaba,34.68,13.75,2.7
1173,PROD-001174,Avery Reactive homogeneous Internet solution C...,Office Supplies,Calendars,Avery,Asian Manufacturing,71.13,25.42,3.6
1174,PROD-001175,Office Depot Enterprise-wide systemic paradigm...,Office Supplies,Calendars,Office Depot,Amazon Supply,87.88,28.58,2.9

___
## Analisando cada Data frame
___

### 1. Customer

In [18]:
df_customer.info()
df_customer

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                25000 non-null  object
 1   customer_name              25000 non-null  object
 2   customer_age               25000 non-null  int64
 3   gender                     25000 non-null  object
 4   customer_segment           25000 non-null  object
 5   customer_city              25000 non-null  object
 6   customer_state             25000 non-null  object
 7   customer_country           25000 non-null  object
 8   region                     25000 non-null  object
 9   customer_postal_code       25000 non-null  int64
 10  customer_acquisition_cost  25000 non-null  float64
dtypes: float64(1), int64(2), object(8)
memory usage: 2.1+ MB

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...,...
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

A tipagem está correta, não temos registros de valores nulos presentes no df. Vemos que a feature *'customer_postal_code'* é desnecessária.

In [19]:
df_customer=df_customer.drop(columns='customer_postal_code')
df_customer

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,41.34
...,...,...,...,...,...,...,...,...,...,...
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,14.92
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,52.38

In [20]:
df_customer.describe()

       customer_age  customer_acquisition_cost
count  25000.000000               25000.000000
mean      45.907840                  42.159750
std       16.454286                  21.692648
min       18.000000                   5.010000
25%       32.000000                  23.297500
50%       46.000000                  41.980000
75%       60.000000                  61.130000
max       74.000000                  79.990000

### 2. Sales

In [21]:
df_sales.info()
df_sales

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  object
 1   order_date                138116 non-null  object
 2   order_time                138116 non-null  object
 3   order_status              138116 non-null  object
 4   sales_channel             138116 non-null  object
 5   customer_id               138116 non-null  object
 6   customer_name             138116 non-null  object
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  object
 9   customer_segment          138116 non-null  object
 10  customer_type             138116 non-null  object
 11  customer_city             138116 non-null  object
 12  customer_state            138116 non-null  object
 13  customer_country          138116 non-null  object
 14  region                    138116 non-null  object
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  object
 17  payment_status            138116 non-null  object
 18  currency                  138116 non-null  object
 19  shipping_method           138116 non-null  object
 20  warehouse                 138116 non-null  object
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  object
 24  return_status             9462 non-null    object
 25  return_reason             9462 non-null    object
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  object
 28  customer_review           113559 non-null  object
 29  marketing_channel         138116 non-null  object
 30  campaign_name             54883 non-null   object
 31  coupon_code               27614 non-null   object
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), object(27)
memory usage: 47.6+ MB

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,8.84,14.28,6.15,224.42,101.77,116.50,51.91,18182.63,True,14
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,0.00,147.30,9.18,2260.80,1246.73,1004.89,44.45,10004.74,True,10
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,0.00,372.37,26.94,2261.16,970.95,1263.27,55.87,16442.68,True,15
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,174.60,130.58,84.39,2080.38,1042.40,953.59,45.84,8047.00,True,5
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,417.27,102.26,9.09,1572.22,884.46,678.67,43.17,4107.38,True,5

vamos alterar a tipagem de *'order_date'* e *'order_time'*

In [22]:
df_sales['order_datetime']=pd.to_datetime((df_sales['order_date'] + ' ' + df_sales['order_time']),format='%Y-%m-%d %H:%M:%S')
df_sales=df_sales.drop(columns=['order_date','order_time'])
df_sales

,order_id,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,customer_type,customer_city,...,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count,order_datetime
0,ORD-301242,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,Loyal,Lake Williamberg,...,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11,2023-11-06 16:37:47
1,ORD-773460,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,Loyal,Kristyport,...,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11,2025-12-24 01:22:36
2,ORD-449374,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,Loyal,Singletonhaven,...,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6,2021-07-05 14:24:21
3,ORD-567636,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,Loyal,Wigginsstad,...,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7,2023-01-21 07:20:26
4,ORD-820028,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,Loyal,New Michaelton,...,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8,2022-05-13 09:46:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,ORD-481534,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,Loyal,Lake Danielville,...,14.28,6.15,224.42,101.77,116.50,51.91,18182.63,True,14,2025-09-27 13:00:50
138112,ORD-487614,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,Loyal,Debrafort,...,147.30,9.18,2260.80,1246.73,1004.89,44.45,10004.74,True,10,2023-07-22 09:13:25
138113,ORD-248062,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,Loyal,Mcmillanshire,...,372.37,26.94,2261.16,970.95,1263.27,55.87,16442.68,True,15,2025-09-08 18:30:32
138114,ORD-252033,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,Loyal,South Joshuafort,...,130.58,84.39,2080.38,1042.40,953.59,45.84,8047.00,True,5,2022-04-06 14:50:07
138115,ORD-528577,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,Loyal,Brianview,...,102.26,9.09,1572.22,884.46,678.67,43.17,4107.38,True,5,2022-11-23 11:46:00

As features abaixo possuem valores nulos, vamos avaliar.
* delivery_days             
* estimated_delivery_days   
* return_status             
* return_reason 
* customer_rating 
* review_sentiment 
* customer_review 
* campaign_name             
* coupon_code

In [28]:
print(df_sales.shape)
df_sales.isna().sum()

(138116, 45)

order_id                         0
order_status                     0
sales_channel                    0
customer_id                      0
customer_name                    0
customer_age                     0
gender                           0
customer_segment                 0
customer_type                    0
customer_city                    0
customer_state                   0
customer_country                 0
region                           0
customer_postal_code             0
payment_method                   0
payment_status                   0
currency                         0
shipping_method                  0
warehouse                        0
delivery_days                24557
estimated_delivery_days      24557
delivery_status                  0
return_status               128654
return_reason               128654
customer_rating              24557
review_sentiment             24557
customer_review              24557
marketing_channel                0
campaign_name                83233
coupon_code                 110502
loyalty_points_earned            0
loyalty_points_redeemed          0
quantity                         0
gross_sales                      0
discount_amount                  0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0
profit_margin_percentage         0
customer_lifetime_value          0
is_repeat_customer               0
customer_order_count             0
order_datetime                   0
dtype: int64

In [31]:
display(df_sales.groupby('delivery_status')['delivery_days'].size())

display(df_sales.groupby('delivery_status')['estimated_delivery_days'].size())

delivery_status
Cancelled    24557
Delayed      16886
Early         9757
On Time      86916
Name: delivery_days, dtype: int64

delivery_status
Cancelled    24557
Delayed      16886
Early         9757
On Time      86916
Name: estimated_delivery_days, dtype: int64

Pelas tabelas acima, vemos que os registros do 'delivery_status'=='Cancelled' tem a mesma quantidade de registro para dados nulos para as features *delivery_days* e *estimated_delivery_days*. Podemos simplesmente deletar o status de Cancelled do df.

In [32]:
df_sales=df_sales[df_sales['delivery_status']!='Cancelled']
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113559 entries, 0 to 138115
Data columns (total 45 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  113559 non-null  object
 1   order_status              113559 non-null  object
 2   sales_channel             113559 non-null  object
 3   customer_id               113559 non-null  object
 4   customer_name             113559 non-null  object
 5   customer_age              113559 non-null  int64
 6   gender                    113559 non-null  object
 7   customer_segment          113559 non-null  object
 8   customer_type             113559 non-null  object
 9   customer_city             113559 non-null  object
 10  customer_state            113559 non-null  object
 11  customer_country          113559 non-null  object
 12  region                    113559 non-null  object
 13  customer_postal_code      113559 non-null  int64
 14  payment_method            113559 non-null  object
 15  payment_status            113559 non-null  object
 16  currency                  113559 non-null  object
 17  shipping_method           113559 non-null  object
 18  warehouse                 113559 non-null  object
 19  delivery_days             113559 non-null  float64
 20  estimated_delivery_days   113559 non-null  float64
 21  delivery_status           113559 non-null  object
 22  return_status             0 non-null       object
 23  return_reason             0 non-null       object
 24  customer_rating           113559 non-null  float64
 25  review_sentiment          113559 non-null  object
 26  customer_review           113559 non-null  object
 27  marketing_channel         113559 non-null  object
 28  campaign_name             45305 non-null   object
 29  coupon_code               22683 non-null   object
 30  loyalty_points_earned     113559 non-null  int64
 31  loyalty_points_redeemed   113559 non-null  int64
 32  quantity                  113559 non-null  int64
 33  gross_sales               113559 non-null  float64
 34  discount_amount           113559 non-null  float64
 35  tax_amount                113559 non-null  float64
 36  shipping_cost             113559 non-null  float64
 37  net_sales                 113559 non-null  float64
 38  product_cost              113559 non-null  float64
 39  profit                    113559 non-null  float64
 40  profit_margin_percentage  113559 non-null  float64
 41  customer_lifetime_value   113559 non-null  float64
 42  is_repeat_customer        113559 non-null  bool
 43  customer_order_count      113559 non-null  int64
 44  order_datetime            113559 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(12), int64(6), object(25)
memory usage: 39.1+ MB

Com isso já resolvemos boa parte do nosso df. Vamos olhar agora para as features *return_status* e *return_reason*. As colunas não tem nenhum registro, vamos tirar do df.

In [34]:
df_sales=df_sales.drop(columns=['return_status','return_reason'])
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113559 entries, 0 to 138115
Data columns (total 43 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  113559 non-null  object
 1   order_status              113559 non-null  object
 2   sales_channel             113559 non-null  object
 3   customer_id               113559 non-null  object
 4   customer_name             113559 non-null  object
 5   customer_age              113559 non-null  int64
 6   gender                    113559 non-null  object
 7   customer_segment          113559 non-null  object
 8   customer_type             113559 non-null  object
 9   customer_city             113559 non-null  object
 10  customer_state            113559 non-null  object
 11  customer_country          113559 non-null  object
 12  region                    113559 non-null  object
 13  customer_postal_code      113559 non-null  int64
 14  payment_method            113559 non-null  object
 15  payment_status            113559 non-null  object
 16  currency                  113559 non-null  object
 17  shipping_method           113559 non-null  object
 18  warehouse                 113559 non-null  object
 19  delivery_days             113559 non-null  float64
 20  estimated_delivery_days   113559 non-null  float64
 21  delivery_status           113559 non-null  object
 22  customer_rating           113559 non-null  float64
 23  review_sentiment          113559 non-null  object
 24  customer_review           113559 non-null  object
 25  marketing_channel         113559 non-null  object
 26  campaign_name             45305 non-null   object
 27  coupon_code               22683 non-null   object
 28  loyalty_points_earned     113559 non-null  int64
 29  loyalty_points_redeemed   113559 non-null  int64
 30  quantity                  113559 non-null  int64
 31  gross_sales               113559 non-null  float64
 32  discount_amount           113559 non-null  float64
 33  tax_amount                113559 non-null  float64
 34  shipping_cost             113559 non-null  float64
 35  net_sales                 113559 non-null  float64
 36  product_cost              113559 non-null  float64
 37  profit                    113559 non-null  float64
 38  profit_margin_percentage  113559 non-null  float64
 39  customer_lifetime_value   113559 non-null  float64
 40  is_repeat_customer        113559 non-null  bool
 41  customer_order_count      113559 non-null  int64
 42  order_datetime            113559 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(12), int64(6), object(23)
memory usage: 41.4+ MB

Vamos nos concentrar agora com *'campaign_name'* e '*coupon_code*'

In [36]:
df_sales['campaign_name'].value_counts()

campaign_name
Default_Campaign      19028
Google_Shopping        2275
Google_Search_Q1       2263
Google_Display         2243
FB_Retargeting         1890
Friend_Invite          1856
FB_Dynamic             1850
Referral_Program       1778
FB_Prospecting         1758
Insta_Influencer       1520
Insta_Reels            1467
Insta_Stories          1451
Abandoned_Cart         1243
Weekly_Newsletter      1203
Promo_Email            1188
Influencer_Program     1169
Affiliate_Partner      1123
Name: count, dtype: int64

Para campaign_name vamos preencher os registros null como no campaign. Algo semelhante vamos fazer para coupon_code.

In [40]:
df_sales['campaign_name']=df_sales['campaign_name'].fillna('no campaign')
df_sales['coupon_code']=df_sales['coupon_code'].fillna('no coupon')
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113559 entries, 0 to 138115
Data columns (total 43 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  113559 non-null  object
 1   order_status              113559 non-null  object
 2   sales_channel             113559 non-null  object
 3   customer_id               113559 non-null  object
 4   customer_name             113559 non-null  object
 5   customer_age              113559 non-null  int64
 6   gender                    113559 non-null  object
 7   customer_segment          113559 non-null  object
 8   customer_type             113559 non-null  object
 9   customer_city             113559 non-null  object
 10  customer_state            113559 non-null  object
 11  customer_country          113559 non-null  object
 12  region                    113559 non-null  object
 13  customer_postal_code      113559 non-null  int64
 14  payment_method            113559 non-null  object
 15  payment_status            113559 non-null  object
 16  currency                  113559 non-null  object
 17  shipping_method           113559 non-null  object
 18  warehouse                 113559 non-null  object
 19  delivery_days             113559 non-null  float64
 20  estimated_delivery_days   113559 non-null  float64
 21  delivery_status           113559 non-null  object
 22  customer_rating           113559 non-null  float64
 23  review_sentiment          113559 non-null  object
 24  customer_review           113559 non-null  object
 25  marketing_channel         113559 non-null  object
 26  campaign_name             113559 non-null  object
 27  coupon_code               113559 non-null  object
 28  loyalty_points_earned     113559 non-null  int64
 29  loyalty_points_redeemed   113559 non-null  int64
 30  quantity                  113559 non-null  int64
 31  gross_sales               113559 non-null  float64
 32  discount_amount           113559 non-null  float64
 33  tax_amount                113559 non-null  float64
 34  shipping_cost             113559 non-null  float64
 35  net_sales                 113559 non-null  float64
 36  product_cost              113559 non-null  float64
 37  profit                    113559 non-null  float64
 38  profit_margin_percentage  113559 non-null  float64
 39  customer_lifetime_value   113559 non-null  float64
 40  is_repeat_customer        113559 non-null  bool
 41  customer_order_count      113559 non-null  int64
 42  order_datetime            113559 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(12), int64(6), object(23)
memory usage: 41.4+ MB

Agora está tudo correto 😁

In [41]:
df_sales

,order_id,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,customer_type,customer_city,...,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count,order_datetime
0,ORD-301242,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,Loyal,Lake Williamberg,...,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11,2023-11-06 16:37:47
1,ORD-773460,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,Loyal,Kristyport,...,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11,2025-12-24 01:22:36
2,ORD-449374,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,Loyal,Singletonhaven,...,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6,2021-07-05 14:24:21
3,ORD-567636,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,Loyal,Wigginsstad,...,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7,2023-01-21 07:20:26
4,ORD-820028,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,Loyal,New Michaelton,...,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8,2022-05-13 09:46:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138109,ORD-712483,Completed,Mobile App,CUST-006301,Sarah Fitzgerald,73,Male,Business,Returning,Rachelfort,...,16.97,20.54,279.84,137.21,122.09,43.63,2380.81,True,3,2022-03-13 00:04:34
138110,ORD-874457,Completed,Marketplace,CUST-004342,Kenneth Valentine,52,Female,Consumer,Loyal,South Joshuafort,...,69.10,9.60,1065.82,704.12,352.10,33.04,5273.57,True,6,2022-11-16 09:38:04
138111,ORD-481534,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,Loyal,Lake Danielville,...,14.28,6.15,224.42,101.77,116.50,51.91,18182.63,True,14,2025-09-27 13:00:50
138114,ORD-252033,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,Loyal,South Joshuafort,...,130.58,84.39,2080.38,1042.40,953.59,45.84,8047.00,True,5,2022-04-06 14:50:07
138115,ORD-528577,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,Loyal,Brianview,...,102.26,9.09,1572.22,884.46,678.67,43.17,4107.38,True,5,2022-11-23 11:46:00

### 3. Order